### ISSUE TITLE
93-1: Organise vote for LB expansion

### ISSUE THREAD

**Issue by ldcouto** [overturetool/overturetool.github.io#23]
According to the OCP, we must vote over email to change the rules regarding the number of LB members.

PGL will take care of this.
- [x]  Make sure Kei Sato is added to the core mailing list (@pglvdm)
- [ ] Send mail out to the core group regarding the LB expansion

**Comment by nlmave** [comment]
Decision at NM was to appoint LB 2016 with 7 voting members and two observers (MV, PJ).
The (e-mail) vote is to extend the LB to consist of "any odd number of members not exceeding 9".
In case the vote is positive, the OCP will be updated accordingly.

**Comment by pglvdm** [comment]
My vote goes to accept having 9 members of the LB

**Comment by peterwvj** [comment]
I vote for having nine members

**Comment by nlmave** [comment]
I vote to accept the proposal to move to max 9 LB members

**Comment by tomooda** [comment]
I vote for having nine members.

**Comment by gkanos** [comment]
I vote for nine member board

**Comment by ldcouto** [comment]
Nine members vote here too.

**Comment by nickbattle** [comment]
I also vote for nine voting LB members.

**Comment by ardbeg1958** [comment]
I vote for 9 members in LB.

**Comment by leouk** [comment]
Happy with 9 members

**Comment by kgpierce** [comment]
I'm happy with odd number not exceeding 9 :+1: I have also added Dr. K and Luis to LB the mailing list.

**Comment by peterwvj** [comment]
Nine members it is! I'm closing this vote/issue!
