### ISSUE TITLE
Investigate overturetool.org DNS record ownership

### ISSUE THREAD

**Issue by nickbattle** [overturetool/overturetool.github.io#31]
Updating the overturetool.org website, by pushing changes to the overturetool.github.io repository, produces the following rather critical warning:

"The page build completed successfully, but returned the following warning for the master branch: The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site’s DNS records if you’d like it to be available via your custom domain. For more information, see https://help.github.com/en/articles/using-a-custom-domain-with-github-pages. For information on troubleshooting Jekyll see: https://help.github.com/articles/troubleshooting-jekyll-builds"

In order to fix this we’d have to go to the company where we purchased the domain and update the DNS settings. However, it is currently unclear who has the power to do this.

**Comment by nlmave** [comment]
As I already informed @peterwvj: when the web-site was migrated from West Consulting to AAU, the domain was also transferred to AAU (perhaps @lausdahl remembers). 

See the (public) WHOIS info below (obtained via https://www.transip.nl/whois/prm/overturetool.org):

WHOIS-informatie voor overturetool.org
Domain Name: OVERTURETOOL.ORG
Registry Domain ID: D101873008-LROR
Registrar WHOIS Server: whois.rrpproxy.net
Registrar URL: http://www.key-systems.net
Updated Date: 2018-09-04T00:21:19Z
Creation Date: 2003-10-20T19:37:30Z
Registry Expiry Date: 2020-10-20T19:37:30Z
Registrar Registration Expiration Date:
Registrar: Key-Systems GmbH
Registrar IANA ID: 269
Registrar Abuse Contact Email: abuse@key-systems.net
Registrar Abuse Contact Phone: +49.68949396850
Reseller:
Domain Status: ok https://icann.org/epp#ok
Registrant Organization: Aarhus Universitet
Registrant State/Province:
Registrant Country: DK
Name Server: NS3.AU.DK
Name Server: NS4.AU.DK
Name Server: NS5.AU.DK
DNSSEC: unsigned

**Comment by lausdahl** [comment]
The domain is registered to AU and all DNS is also provided by AU as shown above.

https://whois.icann.org/en/lookup?name=overturetool.org

@nickbattle AU IT is the one who can fix all related to the domain. A ticket must be created by an AU employee. 

BTW it expires next year

**Comment by peterwvj** [comment]
A ticket has been now been submitted to AU IT

**Comment by peterwvj** [comment]
OK, the DNS records have been updated. The page seems to generate correctly, and I'm not getting any warnings. Closing this issue.
